@extends('front.app')
@section('content')
    <div class="title" data-aos="fade-up">
        <div class="titleText">Cookies Policy</div>
        <div class="borderTitle"></div>
    </div>
        <div class="infoWrap">
            <div class="infoText">
                <h3>For statistical data, irish-safetytraining.com places a cookie (small text file) in your computer.</h3> <br>
                They are not virus spreaders, and cannot be used to search your hard drive. This website uses Google Analytics, a web analytics service provided by Google, Inc. (Google).  Google Analytics uses cookies, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
                <br>
                Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage.  Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Googles behalf. Google will not associate your IP address with any other data held by Google.  You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.
                <br>
                By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
            </div>
        </div>
    </div>
@endsection
